### ISSUE TITLE
Predicates for string line count

### ISSUE THREAD

**Issue by Narann** [assert-rs/predicates-rs#103]
Hello,

First, thanks for your hard work on this crate, I use it with `assert_cmd` and it's easy to both read and use. :)

I test every line, of my output, but I want to be sure I didn't miss anything.

Is there any hope to see a predicate for line count ?

Like a `predicate::str::line_count(5)` to check the output line count is `5` ?

Hope this feature make sense and will brings some interest.

Keep the good work!

**Comment by epage** [comment]
Something like this could be added but I'd like to better understand the use case.  In what situation do you know the number of lines but only check a subset of the content?

**Comment by Narann** [comment]
Thanks for `predicates::str::similar`, I will try it. :)

The second example lost looks less explicit than, for example:

```rust
predicate::str::lines_contains(["my line", "my other line"])
```

But I'm not experienced enough with rust to have strong opinion and maybe what you write make more sense. rust community seems to encourage highly nested functional style. Nothing wrong with that, I'm just not used to it.

I don' want to take you precious time anymore. I will try with:

```rust
predicate::str::is_match("\n").unwrap().count(3)
```

Seems to be what I want.

Keep the good work and have a nice day! :)

**Comment by Narann** [comment]
I actually have a situation where the output count (line count) is known, but the order is not, this means `predicates::str::similar` almost always fail.

**Comment by epage** [comment]
Thats too bad it doesn't work for your case but I like the `is_match` approach.  I think using that more flexible tool might be better than directly baking this in but feel free to suggest otherwise!
