### ISSUE TITLE
Should Diffs be `diff` style?

### ISSUE THREAD

**Issue by epage** [assert-rs/predicates-rs#105]
https://github.com/assert-rs/assert_cmd/issues/121 is an example of long output.  We end up showing both sides of the Diff, so it seems redundant to show the unchanged lines as well. Maybe we should only show changed lines.

**Comment by ajeetdsouza** [comment]
As long as we're only printing one diff rather than both sides separately, I think the redundancy is mitigated. Removing unchanged lines may or may not work for all use cases, perhaps that should be configurable.
