### ISSUE TITLE
Show faulty line in DifferencePredicate

### ISSUE THREAD

**Issue by Chewie** [assert-rs/predicates-rs#112]
Heya,

The regular assert_eq! macro provides the line containing the assert in its output:

```
thread 'main' panicked at 'assertion failed:  `(left == right)`
  left: `4`,
 right: `2`, tests/test.rs:112:5
```
This information can be parsed by editors like Vim to fill the quickfix list automatically and jump to the error, which is very helpful.

Unfortunately, the DifferencePredicate doesn't show this information:

```
---- test_no_yaml stdout ----
thread 'main' panicked at 'Unexpected stdout, failed diff var original
├── original: No test case found. Exuting.

├── diff: 
--- value	expected
+++ value	actual
@@ -1 +1 @@
-No test case found. Exuting.
+No test case found. Exiting.

└── var as str: No test case found. Exiting.
```

Would it be possible to add this information to the output?

**Comment by Chewie** [comment]
I've been playing with [similar](https://github.com/mitsuhiko/similar) and it's companion [similar-asserts](https://github.com/mitsuhiko/similar-asserts) as a replacement of differences.rs, and the result is very clean. Maybe the predicate could make use of this crate?

**Comment by epage** [comment]
This crate aims to be the low level mechanism for implementing crates like that, like [assert_that](https://docs.rs/assert_that/0.1.2/assert_that/) or [assert_cmd](https://github.com/assert-rs/assert_cmd).

To get this functionality, it either needs to come via a macro or the recent [https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1460-2020-08-27](track_callers) attribute

For my crates, I've created https://github.com/assert-rs/assert_cmd/issues/133 and https://github.com/assert-rs/assert_fs/issues/68
