### ISSUE TITLE
[Feature Request] Make `not` and `predicates::PredicateBooleanExt` more visible in docs

### ISSUE THREAD

**Issue by Derpford** [assert-rs/predicates-rs#120]
I'm working on unit tests for a CLI tool, and I need to verify that the tool does *not* add files to a list inside the config file under certain conditions (i.e., dotfiles, files that aren't on the list of types to track, etc).

As of right now, I'm using a series of `contains` predicates alongside `assert_fs`, with `#[should_panic]`, like so:

```rust
#[test]
#[should_panic]
fn test_config_fail() {
  let mut temp = assert_fs::TempDir::new().unwrap();
  make_test_folders(&mut temp).unwrap();
  // Command runs here.
  // ...
  let cfg = temp.child("./config.file");
  cfg.assert(predicate::str::contains(".invisible.txt"));
  cfg.assert(predicate::str::contains("whoops.md"));
  //...
}
```

However, there's a problem with this approach. If the first assert panics, as it should...the rest of the asserts are never touched, because the first one panicked!

I need a way to invert a `contains` predicate--that is, I need something that checks to make sure a substring *doesn't* exist in a target string. It's not practical for me to use the `ne` predicate, because A) the config file contains a lot of lines and B) the order the config file initially puts files in is not deterministic, so it would be prone to false negatives.

**Comment by epage** [comment]
We do provide [`not` on an extension trait](https://docs.rs/predicates/latest/predicates/boolean/trait.PredicateBooleanExt.html#method.not).  Normally we would only provide additional variants of a predicate on top of what you can build up if there is some customization to the formatting we want.  I've not been able to think of some custom formatting a `doesnt_contain` would provide.

We probably need to raise the visibility of the `not` predicate in the documentation.

**Comment by Derpford** [comment]
So I tried adding `not()` to my predicates, like so:
```rust
cfg.assert(predicate::str::contains("example.foo").not());
```

And I got the following error:
![image](https://user-images.githubusercontent.com/10187719/156428412-e5829c45-bc29-42f2-b0df-46ad2bb0d7fa.png)

It seems that `contains` simply doesn't have `not()`.

**Comment by epage** [comment]
`not` is on an extension trait.  You'd need to `use predicates::PredicateBooleanExt;` though I'm surprised the compiler didn't tell you that (it usually does) so I worry something else might also be going on that we'll need to debug.

**Comment by Derpford** [comment]
Ah, yeah, that was a couple lines up. Lemme try again...
