### ISSUE TITLE
Symlinks pointing to regular files are detected as regular files

### ISSUE THREAD

**Issue by SoresViktor** [assert-rs/predicates-rs#139]
Here, on line 35, I think it should be ```file_type```, not ```path```:
https://github.com/assert-rs/predicates-rs/blob/8204e4496cd23358fae6a15ac04aa742e25242ab/src/path/ft.rs#L25-L39
[Path::is_file](https://doc.rust-lang.org/std/path/struct.Path.html#method.is_file) always follows symlinks and will return true if the symlink points to a regular file.

This is probably the root cause of assert-rs/assert_fs#70.

**Comment by epage** [comment]
Thanks for catching that!

**Comment by SoresViktor** [comment]
Wow, fastest fix ever.
