### ISSUE TITLE
MSRV change to 1.64.0 breaks the MSRV of other crates

### ISSUE THREAD

**Issue by HampusMat** [assert-rs/predicates-rs#148]
The change of the MSRV to 1.64.0 is quite troublesome as it breaks the MSRV of other crates. For example, Mockall. And likely many more.

I noticed this when testing a library crate of mine on Rust 1.63.0 two days ago.

Is there any way this can be resolved? Does workspace inheritance really need to be used?

**Comment by epage** [comment]
Each package is responsible for its own MSRV.  I would recommend checking in a `Cargo.lock` file (the cargo guidance on this will soon be changing, see rust-lang/cargo#8728) and using `cargo update -p predicates --precise ...` to set to a version that is compatible with your MSRV.  Longer term, I'm hoping we can make cargo automatically do this for you.  That is my next project once I wrap up some misc tasks.

**Comment by HampusMat** [comment]
Thank you for such a fast response! I had no idea that the Cargo.lock policy is changing. Keeping the lock file makes things a lot easier for sure.

Thank you.
