### ISSUE TITLE
Publish a new release to offer access to itertools 0.11

### ISSUE THREAD

**Issue by poliorcetics** [assert-rs/predicates-rs#153]
Now that `itertools 0.11` has been merged, is it possible to release a new version ? 

Notably, there is `assert_cmd` that is used quite a lot that would then be up-to-date transitively.

If there's something to do in preparation and you have an issue for it, I can take a look and try to help!

**Comment by epage** [comment]
3.0.4 is now out

(normally I only do release for user-facing changes; internal changes are on request)
