### ISSUE TITLE
Enable cron builds on appveyor

### ISSUE THREAD

**Issue by nastevens** [assert-rs/predicates-rs#16]
I've enabled daily builds on travis, but you'll have to enable on appveyor @epage

**Comment by epage** [comment]
I'm curious, what is your goal with daily builds?

**Comment by nastevens** [comment]
We're doing a build with nightly Rust builds, which change daily. If one of those transiently breaks something (which sometimes happens) it doesn't warrant someone jumping to fix an issue that may not be there. But during that time the badge will show a failing build which is not ideal. I'd like to minimize that cycle time.

I think the other approach is to build nightly build not cause CI failures if the nightly build fails. This seems like a bit of a cop-out since there will be people using nightly due to features not yet landed in stable.

Reverse question - if doing refresh builds anyway, is there a reason you'd prefer to do them less frequently?

**Comment by nastevens** [comment]
Weird on the AppVeyor stuff - I understand not enabling it by default, but requiring communication to enable seems excessive. I'm fine with just saying "forget it".

I think your work to consolidate best CI practices has some good points on frequency - I'm going to bump down predicates-rs to weekly in Travis for now. Monthly feels too long, but I might change my mind in the future 🤷‍♂️
