### ISSUE TITLE
Refactor API / source layout?

### ISSUE THREAD

**Issue by epage** [assert-rs/predicates-rs#17]
The layout in the docs / source feels strange with everything buried under the `predicate` module.  The goal seems to be to allow imports like:
```rust
use predicates::{predicate, Predicate};
```

Proposal:
- Move all predicate modules into the root with a `pub use` in `lib.rs`
- Move `Predicate` and `BoxedPredicate` in dedicated private files in the root with a `pub use` in `lib.rs`.
- Create a `prelude` module that contains
  - `Predicate`
  - `predicate` module which only re-exports the factory functions
    - Add a note to the factory functions about this
    - Add a note to the `*Predicate`s about using the factories from `predicate`.

The standard import would now look like:
```rust
use predicates::prelude::*;
```

Benefits
- Standard import is more consistent with regular stuff
- Source and docs organization will be less nested
- Docs will be a little more organized
- The scope of the `predicate` module will be narrowed to just factories which imo makes the intent / starting point more clear.

**Comment by nastevens** [comment]
The source layout was an artifact of some early work to include "adapter" types, not unlike what is talked about in #21. The idea was that there would be two namespaces in the root, `predicate` and `adapter`. The adapters never materialized, but the layout remains.

The layout you describe seems much more usable, I give it a 👍 .
