### ISSUE TITLE
API doesn't work well with distinct owned / ref types

### ISSUE THREAD

**Issue by epage** [assert-rs/predicates-rs#20]
`EqPredicate` stores `T` and its `eval` takes a `&T`.  But what about `Vec`/`slice`, `String`/`str`, and `PathBuf`/`path`? 

### Exploration Summary

After making `Predicate` use generics rather than associated types (see #29)

Dead ends
- `Predicate { eval<I: AsRef<Item>>(&self, item: I) }`: [not object-safe](https://doc.rust-lang.org/1.16.0/book/trait-objects.html#object-safety) which means we can't `Box<Predicate>` or `&Predicate`.
- `Predicate { eval(&self, item: Item) }` (ie `Item=&str` rather than `Item=str`): violates borrow checker in boolean predicates
- Above with `Item: Copy`: Lifetime issues ([branch](https://github.com/epage/predicates-rs/tree/borrow_copy))
- `impl Predicate<AsRef<T>> for EqPredicate<T>`: No AsRef implemented for numeric types
- `impl Predicate<Borrow<T>> for EqPredicate<T>`: `Sized` issues ([branch](https://github.com/epage/predicates-rs/tree/borrow_borrow))

Options:
- Create an `AsRef` adapter

**Comment by nastevens** [comment]
Commented in #18 but make sense to add here.  The `Predicate` trait could be changed to accept `Borrow<T>` instead of `&T`. Since `Borrow<T>` is implemented for `&T`, this probably won't even end up being a breaking change, and would allow things using String and Vec to be way more ergonomic.

**Comment by epage** [comment]
In looking at this, I also might need to change the Predicate trait. In researching, it seems the recommendation is to use associative types for return types (don't need to mention type on every call) and generics for parameters (allows multiple trait implementations per struct).

**Comment by epage** [comment]
Ok, got a branch with `Predicate` using generics.

- Can't make `eval` accept `AsRef` because that will make the [function not object-safe](https://doc.rust-lang.org/1.16.0/book/trait-objects.html#object-safety) which means we can't `Box<Predicate>` or `&Predicate`.
- Tried changing eval's signature to `Item` from `&Item`, putting the burden of `&` on the client.  This causes borrow check violations in the boolean predicates.  The only way to make this route work is if we required `Item` to be copyable.

So remaining areas to explore
- `Item: Copy`
- Just modifying `EqPredicate`s `impl` to more easily allow the `Predicate` to borrow `EqPredicate`s owned type

**Comment by epage** [comment]
Had some time to evaluate this.  The work for #29 is probably the best we'll get.

**Comment by epage** [comment]
So while we need to address `Predicate<str>` for `EqPredicate<String>`, another angle on this is passing a `&'static str` to `EqPredicatè and being able to get a `Predicate<str>`.

**Comment by epage** [comment]
#49 is another step towards addressing this
