### ISSUE TITLE
Consolidate predicate efforts?

### ISSUE THREAD

**Issue by epage** [assert-rs/predicates-rs#5]
I've created some predicates for [assert_cli](https://github.com/assert-rs/assert_cli/blob/master/src/output.rs) and expect to be creating more.

I'm wondering if you want to join efforts in providing general predicates for exposure in different APIs

- Would you be interested in moving to the new `assert.rs` org with the intent of having others help support you in maintaining this crate?
- Are you interested in more and more complex predicates being added?  As one example, assert_cli will show a diff if two strings are different
- How amenable are you to the API evolving to support additional or different needs?  For example, a version of `eval` that reports what didn't match of the expression?

RE consolidating on orgs, I'm inspired by killercups #rust2018  post:

> There is no reason why so many popular crates should live in user-repos instead of in community-managed organizations (speaking in Github terms). Writing and then publishing a bunch of code as a crate one thing, but maintaining it, fixing bugs, replying to issues and pull requests, that takes up a lot of time as well. Time, that a lot of developers don't have, or don't want to invest. cargo-edit, for example, which lives under my Github username, has two wonderful maintainers, who are more active than I am. But should I create a cargo-edit organization and move the repo there? If there was a good and definitive answer, which would neither make me deal with the organizational aspects not result in accumulating lot of junk code, I'd be really happy.

https://deterministic.space/rust-2018.html#aim-for-long-term-stability-of-the-library-ecosystem

**Comment by nastevens** [comment]
Sorry for the delay, I somehow missed/didn't receive an alert from GitHub.

My answers, in order, are yes, yes, and yes! This was a crate put together for use in some code for work and I was just hoping it might end up being useful for someone else. This has actually been used in production and "just works" so I haven't had much occasion to do anything else with it, which is why it has been inactive.

I can transfer to `assert-rs` any time, just let me know.

**Comment by epage** [comment]
Great! I've contacted the owner on `assert-rs` to get you added as a member.  Not sure if that is needed before transferring but something that will need to be done anyways.

We've not fully worked out governance on these communal orgs.  If you have preferences on who are approved reviewers or anything else, let us know.  If nothing else, we can always create a "predicates" team that you can manage for your repo.

**Comment by nastevens** [comment]
Transfer is done, I've added the CLIQuE team as collaborators for now, we can revisit teams if needed. We'll want to swap out `nastevens` for `assert-rs` where appropriate in the README - I've opened #6 to track that. I'd recommend opening tracking issues for the other improvements you mentioned above and then closing this issue.

Thanks again for bringing this up!

**Comment by epage** [comment]
Good enough for now on creating new issues, closing.
