### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by asomers** [assert-rs/predicates-rs#77]
Could you please release a new version of predicates and predicates-tree?  As soon as you do that, I'll be able to publish the first version of my new crate!

**Comment by epage** [comment]
Sorry about that; I forgot there was something to release (usually do it immediately after each submission but this fell through the cracks).

I've kicked off `cargo publish` and should have v1.0.1 out soon.

> predicates-tree

Why is this needed?

**Comment by asomers** [comment]
Thanks!  Regarding predicates-tree, a release may not be needed.  I just assumed that the two were released on lock-step and I didn't check whether I was using any newer changes to predicates-tree.  It turns out I'm not.
