### ISSUE TITLE
Build broken with float-cmp 0.4.1

### ISSUE THREAD

**Issue by brson** [assert-rs/predicates-rs#78]
After updating my lockfile such that float-cmp went from 0.4.0 to 0.4.1 I see:

```
error[E0061]: this function takes 2 parameters but 3 parameters were supplied
  --> /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/predicates-1.0.1/src/float/close.rs:86:18
   |
86 |         variable.approx_eq(&self.target, self.epsilon, self.ulps)
   |                  ^^^^^^^^^ expected 2 parameters
```

**Comment by PascalPrecht** [comment]
Just ran into the same thing. There was a breaking change introduced in float-cmp a long long time ago but has only been released yesterday: https://github.com/mikedilger/float-cmp/issues/17

**Comment by mikedilger** [comment]
I'm terribly sorry for breaking float-cmp. I've yanked 0.4.1

**Comment by epage** [comment]
Understandable.  Stuff like that happens.
