### ISSUE TITLE
The crates.io release and the master branch of this repository don't match

### ISSUE THREAD

**Issue by Eijebong** [assert-rs/predicates-rs#86]
Hey,

so the released version on crates.io is from commit https://github.com/assert-rs/predicates-rs/commit/a9503ad602bf614a6e504bea22cde39546847c09 (https://docs.rs/crate/predicates/1.0.2/source/.cargo_vcs_info.json) which isn't on any branch but does exist on the repository. That's confusing because master says float-cmp should be 0.6 while on crates.io it's currently 0.5.

I think it would be a good idea to release the current master branch as a new version to fix that discrepancy between the repository and crates.io

**Comment by est31** [comment]
Diff between the two commits: https://github.com/assert-rs/predicates-rs/compare/cd6d27690f7c053e43fcb3cb89d7284f0fd7cb4f..a9503ad602bf614a6e504bea22cde39546847c09

**Comment by epage** [comment]
Released. I had done a release on my local copy without realizing it was out of date and didn't correct it since I was unaware that the difference was enough to matter.

Probably should add a check in cargo-release to see if the local branch is behind the remote.
